---
version: '3'

services:
    php-dev:
        image: hanabosocom/php-dev:php-8.2-alpine
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - COMPOSER_HOME=${HOME}/dev/.composer
            - KERNEL_CLASS=RabbitBundleTests\app\Kernel
            - RABBITMQ_DSN=amqp://rabbitmq:5672/

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - ${DEV_IP}:15672:15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq

volumes:
    rabbitmq: {}
