---
version: '3'

services:
    php-dev:
        image: dkr.hanaboso.net/hanaboso/rabbit-mq-bundle/dev:dev
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
            - ${HOME}/.composer:/srv/.composer
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}

    rabbitmq:
        image: rabbitmq:management-alpine
        volumes:
            - rabbitmq:/var/lib/rabbitmq

volumes:
    rabbitmq: {}
