---
version: '3'

services:
    php-dev:
        image: hanabosocom/php-dev:php-7.4
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:${SSH_AUTH}
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - COMPOSER_HOME=${HOME}/dev/.composer
            - KERNEL_CLASS=RabbitBundleTests\app\Kernel
            - RABBITMQ_DSN=amqp://rabbitmq:5672/

    rabbitmq:
        image: rabbitmq:management-alpine
        volumes:
            - rabbitmq:/var/lib/rabbitmq

volumes:
    rabbitmq: {}
